#Open API Specification

openapi: 3.0.0
info:
  title: REST challenge API
  description: REST API for the RAVN REST challenge
  version: 0.0.1
# servers:
  # - url: http://api.example.com/v1
  #   description: Optional server description, e.g. Main (production) server
  # - url: http://staging-api.example.com
  #   description: Optional server description, e.g. Internal staging server for testing
paths:
  # /users:
  #   get:
  #     summary: Returns a list of users.
  #     description: Optional extended description in CommonMark or HTML.
  #     responses:
  #       '200':    # status code
  #         description: A JSON array of user names
  #         content:
  #           application/json:
  #             schema:
  #               type: array
  #               items:
  #                 type: string

# /signin

# /signout
# /accounts
  /accounts:
    get:
      summary: Returns a list of accounts
      responses:
        "200":
          description: "succesful operation"
    post:
      summary: Create post
      responses:
        "200":
          description: "post created"


# /accounts/:id
# /account/:id
# /account/:id
# /account/:id

# /posts
  /posts:
    get:
      summary: Returns a list of published posts
      responses:
        "200":
          description: "succesful operation"
    post:
      summary: Create post
      responses:
        "200":
          description: "post created"

  /posts/{postid}:
    get:
      summary: Returns a single post
      responses:
        "200":
          description: "succesful operation"
        "400":
          description: "invalid id"
        "404":
          description: "post not found"
    put:
      summary: Update an existing post
      responses:
        "200":
          description: "succesful update"
        "400":
          description: "invalid id"
        "404":
          description: "post not found"
    delete:
      summary: Delete an existing post
      responses:
        "200":
          description: "succesful delete"
        "400":
          description: "invalid id"
        "404":
          description: "post not found"

  /posts/{postid}/like:
    post:
      summary: Give "like" to a post
      responses:
        "200":
          description: "succesful operation"
        "400":
          description: "invalid id"
        "404":
          description: "post not found"
    delete:
      summary: Remove "like" to a post
      responses:
        "200":
          description: "succesful operation"
        "400":
          description: "invalid id"
        "404":
          description: "post not found"

  /posts/{postid}/dislike:
    post:
      summary: Give "dislike" to a post
      responses:
        "200":
          description: "succesful operation"
        "400":
          description: "invalid id"
        "404":
          description: "post not found"
    delete:
      summary: Remove "dislike" to a post
      responses:
        "200":
          description: "succesful operation"
        "400":
          description: "invalid id"
        "404":
          description: "post not found"

  /posts/{postid}/report:
    post:
      summary: Report a post
      responses:
        "200":
          description: "succesful operation"
        "400":
          description: "invalid id"
        "404":
          description: "post not found"
    delete:
      summary: Remove report status to a post
      responses:
        "200":
          description: "succesful operation"
        "400":
          description: "invalid id"
        "404":
          description: "post not found"

# /comments/:postid
# /comments/:postid/:commentid
# /comments/:postid/:commentid


# /comment/:postid/like
# /comment/:postid/dislike
# /comment/:postid/like
# /comment/:postid/dislike

# /comments/:commentid/report

# /posts
# /posts/:userid


# /signup

# /posts/:postid



